### ISSUE TITLE
[依頼]Stream処理について教えてほしいです。

### ISSUE THREAD

**Issue by hayashi0924** [hayashi0924/MagicalBattle#13]
https://github.com/hayashi0924/MagicalBattle/blob/4ca72682e5c78c6a209252fadb26734686cdc693/Main/src/field/Field.java#L58

この部分でバグが出ます。

やりたいこと
①全てのmapから引数（キャラクター名）と同じものを検索。
②当てはまるものがあれば、DOTに変換。
③再度、配列として返す。

現状
キャラクター名が変換されないまま配列となる。

ローカルブランチでは、forを使った処理で解決済みなのですが、stream処理について調べても解決しなかったので質問させていただきました！
こういうもんならこういうもんで覚えます笑

**Comment by mikami0056** [comment]
> キャラクター名が変換されないまま配列となる。

以下と認識しました。
- [move](https://github.com/hayashi0924/MagicalBattle/blob/4ca72682e5c78c6a209252fadb26734686cdc693/Main/src/field/Field.java#L52) を実行した後は、Character がいた元の場所はドットに置き換わるはず
- にもかかわらず、置き変わらずにそのままになっている。

（動作確認していないので間違ってる可能性もありますが）やりたいこととソースコードに乖離はないように見えますが、何かが足りません。
Stream の of, filter, map, toArray メソッドをそれぞれ使っているので、各メソッドの Javadoc を検索して読んでみてください。
特に toArray メソッドの Javadoc を読んでみてください。

**ヒント**
- [ここ](https://github.com/hayashi0924/MagicalBattle/blob/4ca72682e5c78c6a209252fadb26734686cdc693/Main/src/field/Field.java#L56)  で配列を maps として取り出して Stream 処理をかけていますが、その処理が maps に反映されるのか？
```java
    // ex
    String[] names = {"太郎", "次郎", "田中"};

    Stream.of(names) // 配列 を Stream に変換
          .filter(name -> name.equals("田中")) // 田中を抽出
          .map(filteredName -> "一郎") // 一郎に変更
          .toArray(String[]::new); // Stream を 配列に変換

    // 田中 が 一郎に変わっているか？
    System.out.println(Arrays.toString(names));
```


- Stream における副作用について
https://docs.oracle.com/javase/jp/8/docs/api/java/util/stream/package-summary.html

**Comment by mikami0056** [comment]
※本件とは関係ないですがコメント

```java
// toString() を呼ぶとキャラクターの名前が取得できるのかな？
character.toString().equals(characterName);

// 例えば↓とか
character.getName().equals(characterName);

// getName() させたくなかったら↓とか？
character.is(characterName);
```

---

https://github.com/hayashi0924/MagicalBattle/blob/4ca72682e5c78c6a209252fadb26734686cdc693/Main/src/field/Field.java#L40
と
https://github.com/hayashi0924/MagicalBattle/blob/4ca72682e5c78c6a209252fadb26734686cdc693/Main/src/field/Field.java#L61
って同じ？

---

**Comment by hayashi0924** [comment]
[返答]
ご助言ありがとうございます。
報告です！

①filterについて
当てはまる要素のストリーム配列を返すものでした。したがって、今回であればcharacter名のみが返されます。中間処理です。
②toArrayについて
終端処理です。stream要素を配列として返します。したがって、今回であればcharacter名のみの配列が返されます。
③今回の処理について
mapsに反映されません。
　⇨for文内にて処理を開始。メソッドスコープ内にて、mapの書き換え処理を行なっていないため、意味のない処理となっている。

**Comment by hayashi0924** [comment]
[ヒントへの返信]
こう書かれるとめっちゃわかりやすかったです。

①streamが元のデータに及ぼす影響について
namesの要素に変更はありません。
streamは遅延評価のため、書き換える処理はできませんでした。



②副作用について
stream外部への処理は危険なことがわかりました。
並列処理の関係で、元のデータをおかしくする可能性がありました。
streamは単体で処理する必要を学びました。


感想
聞きなれない言葉が沢山出てきて、勉強になりました。
並列処理や、ヒープ領域・スタック領域（本ではプリミティブ型と参照型の話だった）とか、Javaでもまだまだ知らないことだらけだと認識しました！

**Comment by hayashi0924** [comment]
getNameの方にします！

同じでした！別のメソッドに分けてみます！
